version: '3.9'
services:
  frontend-app:
    image: dev-rt-website-image
    container_name: dev-rt-website-container
    build:
      context: ../../
      dockerfile: ./docker/dev/dockerfile
    environment:
      - CMD
    volumes:
      - ../../:/app
    ports:
      - 3000:3000
    env_file:
      - ../../.env