apiVersion: apps/v1
kind: Deployment
metadata:
  name: rt-website-deployment
spec:
  selector:
    matchLabels:
      app: rt-website
  replicas: 1
  template:
    metadata:
      labels:
        app: rt-website
    spec:
      containers:
      - name: dev-rt-website-container
        image: dev-rt-website-image
        imagePullPolicy: Never
        ports:
        - containerPort: 3000