name: Send Deploy Event

on:
  push:
    branches:
      - master

jobs:
  send_event:
    runs-on: ubuntu-latest
    steps:
    - name: Sending Event
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.RT_REPO_TOKEN }}
        repository: eythaann/readable-types
        event-type: trigger-deployment
